Repository sUNC-Utilities/docs.sunc.su, pull requests merged in 2025-05, with the labels that each got.

#38 Add compareinstances & Instances library grammar revision
  docs/Instances/README.md
  docs/Instances/compareinstances.md
  docs/Scripts/getloadedmodules.md
  docs/Scripts/getrunningscripts.md
  docs/Scripts/getscriptbytecode.md
  docs/Scripts/getscripts.md
  docs/Scripts/getsenv.md
  docs/Scripts/loadstring.md
Labels: Technical Accuracy, Wording & Clarity, Complete

#62 Update getconnections admonition
  docs/Signals/getconnections.md
Labels: Wording & Clarity

#73 Explicit WSS check & moved note
  docs/WebSocket/README.md
Labels: Technical Accuracy, Wording & Clarity

#80 add getreg documentation
  docs/Environment/getreg.md
Labels: Technical Accuracy, Wording & Clarity, New function

#92 getgc compliance with contribution guidelines
  docs/Environment/getgc.md
Labels: Wording & Clarity, Invalid Structure / Formatting

#93 Getscripthash wording
  docs/Scripts/getscripthash.md
Labels: Wording & Clarity
